In [ ]:
import numpy as np
import pandas as pd

from utils.load_config import load_config
from utils.load_data import load_pkl

## Data loading

In [ ]:
cfg = load_config()
driams_pkl = cfg["data"]["DRIAMS_REDUCED_PKL"]

In [5]:
driams = load_pkl(driams_pkl)

## Data exploration

In [6]:
print(type(driams))
print(driams.keys())

<class 'dict'>
dict_keys(['data', 'label', 'meta'])


In [7]:
data, label, meta = driams["data"], driams["label"], driams["meta"]

In [8]:
print(f"Spectra matrix shape: {data.shape}")
print(f"Labels shape: {label.shape}")
print(f"Metadata shape: {meta.shape}")

Spectra matrix shape: (39781, 6000)
Labels shape: (39781,)
Metadata shape: (39781,)


In [9]:
print(type(data))
print(type(label))
print(type(meta))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


Take a closer look at each variable to familiarize with its structure

In [10]:
print(data[:5])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [11]:
print(label[:5])

['Klebsiella_Pneumoniae' 'Klebsiella_Pneumoniae' 'Klebsiella_Pneumoniae'
 'Klebsiella_Pneumoniae' 'Klebsiella_Pneumoniae']


In [13]:
print(np.unique(label))

['Enterobacter_cloacae_complex' 'Enterococcus_Faecium' 'Escherichia_Coli'
 'Klebsiella_Pneumoniae' 'Pseudomonas_Aeruginosa' 'Staphylococcus_Aureus']


In [14]:
print(meta)
driams["meta"][10]

[{'hospital': 'DRIAMS_B', 'year': '2018', 'genus': 'Klebsiella', 'species': 'Pneumoniae', 'study': '23a9e0ba-d4b2-40eb-808c-37270a5117dc.txt'}
 {'hospital': 'DRIAMS_B', 'year': '2018', 'genus': 'Klebsiella', 'species': 'Pneumoniae', 'study': '36437826-52fa-4daf-8f2b-4133f4307156.txt'}
 {'hospital': 'DRIAMS_B', 'year': '2018', 'genus': 'Klebsiella', 'species': 'Pneumoniae', 'study': 'da983ae0-e887-4771-bdb1-9a8d564eb017.txt'}
 ...
 {'hospital': 'DRIAMS_C', 'year': '2018', 'genus': 'Enterobacter', 'species': 'Ludwigii', 'study': '28020109560_F1.txt'}
 {'hospital': 'DRIAMS_C', 'year': '2018', 'genus': 'Enterobacter', 'species': 'Ludwigii', 'study': '28030306620_F3.txt'}
 {'hospital': 'DRIAMS_C', 'year': '2018', 'genus': 'Enterobacter', 'species': 'Ludwigii', 'study': '28082703960_A5.txt'}]


{'hospital': 'DRIAMS_B',
 'year': '2018',
 'genus': 'Klebsiella',
 'species': 'Pneumoniae',
 'study': 'b9df08c1-9056-4d77-8774-170546cced42.txt'}

In [15]:
meta_expanded = pd.DataFrame.from_records(list(meta))

In [16]:
print(meta_expanded.shape)
print(type(meta_expanded))

(39781, 5)
<class 'pandas.core.frame.DataFrame'>


In [17]:
meta_expanded.head()

,hospital,year,genus,species,study
0,DRIAMS_B,2018,Klebsiella,Pneumoniae,23a9e0ba-d4b2-40eb-808c-37270a5117dc.txt
1,DRIAMS_B,2018,Klebsiella,Pneumoniae,36437826-52fa-4daf-8f2b-4133f4307156.txt
2,DRIAMS_B,2018,Klebsiella,Pneumoniae,da983ae0-e887-4771-bdb1-9a8d564eb017.txt
3,DRIAMS_B,2018,Klebsiella,Pneumoniae,5e8f4603-1399-4ad5-a618-7e8bf2fc4207.txt
4,DRIAMS_B,2018,Klebsiella,Pneumoniae,ce63ff87-717d-4eac-8dca-590ffa840867.txt


In [18]:
for col in meta_expanded.columns:
    print(f"Number of unique labels for column '{col}': {len(np.unique(meta_expanded[col]))}")
    print(f"Unique labels for column '{col}': {np.unique(meta_expanded[col])}", "\n")

Number of unique labels for column 'hospital': 4
Unique labels for column 'hospital': ['DRIAMS_A' 'DRIAMS_B' 'DRIAMS_C' 'DRIAMS_D'] 

Number of unique labels for column 'year': 4
Unique labels for column 'year': ['2015' '2016' '2017' '2018'] 

Number of unique labels for column 'genus': 6
Unique labels for column 'genus': ['Enterobacter' 'Enterococcus' 'Escherichia' 'Klebsiella' 'Pseudomonas'
 'Staphylococcus'] 

Number of unique labels for column 'species': 10
Unique labels for column 'species': ['Aeruginosa' 'Asburiae' 'Aureus' 'Cloacae' 'Coli' 'Faecium' 'Hormaechei'
 'Kobei' 'Ludwigii' 'Pneumoniae'] 

Number of unique labels for column 'study': 39781
Unique labels for column 'study': ['00012236-6e95-4810-b400-fa88c76c6329_MALDI1.txt'
 '000297cd-7cea-421b-ac23-b1a095a7c976_MALDI1.txt'
 '000a2090-67fb-4556-8d34-3b758508be98.txt' ...
 'fff7370f-38a6-4aeb-be3a-331b5efdc353_MALDI1.txt'
 'fffb1052-eb30-4f1b-a1a2-3051267be19f_3313.txt'
 'fffc5f05-d2a1-42e3-a502-667d37908295_3312.txt'] 

